In [19]:
import pandas as pd #in this line pandas acts as pd instead of pandas and its known as pandas package

In [2]:
dataset=pd.read_csv("Salary_Data.csv")
#dataset is a structure set of data and then pd.read_csv means it import a csv file to dataframe format

In [3]:
dataset #dataset: it containt some data into it

    YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [4]:
independent=dataset[["YearsExperience"]]#independent is a variable name its known for input variable and in this line we seperate the input column by using this variable name

In [5]:
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [6]:
dependent=dataset[["Salary"]] #dependent is a output variable , we split the input onput from this line and above lines

In [7]:
dependent

    Salary
0    39343
1    46205
2    37731
3    43525
4    39891
5    56642
6    60150
7    54445
8    64445
9    57189
10   63218
11   55794
12   56957
13   57081
14   61111
15   67938
16   66029
17   83088
18   81363
19   93940
20   91738
21   98273
22  101302
23  113812
24  109431
25  105582
26  116969
27  112635
28  122391
29  121872

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0) 
#in this line we split the train set and the test set sklearn is the library it cointain mechine learning process 
#in this process we can save memory
#we use some parameter into the function such as independent, test size,random state

In [9]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)
# from using sklearn we import the LinearRegression
#regrossor is a variable for this model
#using "=" assigning symbol we assign the variable regressor to linear regression
#whenever we use the fit method to call a fuction it subtitute the values to the variable its just like a maths formulae

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
weight=regressor.coef_
weight
#weight is a variable 
#Coef is nothing but its stores the weight calcution
#"."its known as dot operator its using for calling the object or function

array([[9360.26128619]])

In [11]:
bais=regressor.intercept_
bais
#bais is a variable 
#like coef intercept stores the calcutlation of bais

array([26777.3913412])

In [12]:
y_pred=regressor.predict(X_test)
#y_pred is a variable and predict is fuction of our application
# cross check process for our test data

In [13]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)
# in this line we find the r2 value using sklearn and then write a variable then assign a name for the variable 
#y_test is actual out put
#y_pred is predicted value of our model

In [14]:
r_score
# if our models value is nearly to 1 its a good model

0.9740993407213511

In [15]:
import pickle
filename="finalized_model_linear.sav"
# this is the process to save the model
#pickle is fuction

In [16]:
pickle.dump(regressor,open(filename,'wb'))#wb mean write binary
#using "pickle.dump" we dump the model into the filename

In [17]:
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))# rb mean read binary
result=loaded_model.predict([[14]])
#in this line we load the saved model
#we use the "loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))" this to load the model already saved model
#"loaded_model=" is a variable

In [18]:
result # process to check whether the model is good or bad

array([[157821.04934791]])